# Generated by Django 4.1 on 2022-11-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
