# Generated by Django 4.1 on 2022-09-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('price', models.FloatField(blank=True, default=1, null=True)),
                ('digital', models.BooleanField(default=False, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('product_pic', models.ImageField(default='default.jpg', upload_to='product')),
            ],
        ),
    ]
