# Generated by Django 4.1 on 2022-10-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genres',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
