# Generated by Django 4.1 on 2022-10-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genres',
            field=models.CharField(choices=[('Action', 'Action and adventure'), ('Art', 'Art/architecture'), ('Alternate history', 'Alternate history'), ('Autobiography', 'Autobiography'), ('Anthology', 'Anthology'), ('Biography', 'Biography'), ('Business', 'Business/economics'), ('Children', 'Children'), ('Crafts/hobbies', 'Crafts/hobbies'), ('Classic', 'Classic'), ('Cookbook', 'Cookbook'), ('Comic book', 'Comic book'), ('Diary', 'Diary'), ('Dictionary', 'Dictionary'), ('Crime', 'Crime'), ('Encyclopedia', 'Encyclopedia'), ('Drama', 'Drama'), ('Fairytale', 'Fairytale'), ('Health', 'Health/fitness'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Graphic novel', 'Graphic novel'), ('Home and garden', 'Home and garden'), ('Historical fiction', 'Historical fiction'), ('Humor', 'Humor'), ('Horror', 'Horror'), ('Journal', 'Journal'), ('Mystery', 'Mystery'), ('Math', 'Math'), ('Paranormal romance', 'Paranormal romance'), ('Memoir', 'Memoir'), ('Picture book', 'Picture book'), ('Philosophy', 'Philosophy'), ('Poetry', 'Poetry'), ('Prayer', 'Prayer'), ('Political thriller', 'Political thriller'), ('Religion', 'Religion, spirituality, and new age'), ('Romance', 'Romance'), ('Textbook', 'Textbook'), ('Satire', 'Satire'), ('True crime', 'True crime'), ('Science fiction', 'Science fiction'), ('Review', 'Review'), ('Short story', 'Short story'), ('Science', 'Science'), ('Suspense', 'Suspense'), ('Self help', 'Self help'), ('Thriller', 'Thriller'), ('Sports and leisure', 'Sports and leisure'), ('Western', 'Western'), ('Travel', 'Travel'), ('Young adult', 'Young adult')], default='Textbook', max_length=150),
        ),
    ]
